/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgreePrivacy: typeof import('./../src/components/agree-privacy/index.vue')['default']
    Banner: typeof import('./../src/components/banner/banner.vue')['default']
    Day_hot: typeof import('./../src/components/day_hot/index.vue')['default']
    Index_common: typeof import('./../src/components/index_common/index.vue')['default']
    Movie_list: typeof import('./../src/components/movie_list/index.vue')['default']
    PageNav: typeof import('./../src/components/page-nav/page-nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ZPaging: typeof import('./../src/components/z-paging/components/z-paging/z-paging.vue')['default']
    ZPagingCell: typeof import('./../src/components/z-paging/components/z-paging-cell/z-paging-cell.vue')['default']
    ZPagingEmptyView: typeof import('./../src/components/z-paging/components/z-paging-empty-view/z-paging-empty-view.vue')['default']
    ZPagingLoadMore: typeof import('./../src/components/z-paging/components/z-paging/components/z-paging-load-more.vue')['default']
    ZPagingRefresh: typeof import('./../src/components/z-paging/components/z-paging/components/z-paging-refresh.vue')['default']
    ZPagingSwiper: typeof import('./../src/components/z-paging/components/z-paging-swiper/z-paging-swiper.vue')['default']
    ZPagingSwiperItem: typeof import('./../src/components/z-paging/components/z-paging-swiper-item/z-paging-swiper-item.vue')['default']
  }
}
